### PR TITLE
Rewrote the tvservice_shim for the 4.9 kernel

### PR DESCRIPTION
**Pull request by zjoasan**
Added 
+ more CEA modes (4k resolutions)
+ 4.9 kernel DMT modes too.
+ EDID dump, binary if xxd is installed, hexdemp-text file if not
+ audio capabillities
+ Json dump
+ HDMI turn off / on( with -p and -e)
+ Sets displays prefered mode

Removed
- old code
- non working code

Things needed done:
* clean up the code, example: creating arrays multiple ways, should be unified.
* using echo and printf, might need to be unifide
* using =´command' and =$(command), might be unified too
* Spelll checking, formating checks, remerks checks.
* probebly more things

### CODE REVIEW

**Comment by hissingshark** [comment]
Many thanks for this.
As soon as I've wrapped up the Stretch -> Buster transition I'll get onto it.

**Comment by zjoasan** [comment]
Tried to conform the code, like using $() instead of =`` , removed some other outdate bash-expressions and replaced them with the suggested changes from https://github.com/koalaman/shellcheck

**Comment by hissingshark** [comment]
Thanks.  Removing backticks was one of the things I was going to do.
I switched up to 4.9 again today, so provided it works well enough to do as a daily driver for now I can get testing this.

**Comment by hissingshark** [comment]
Only typos corrected so far.  Functionally it's looking good.

The only bug is the aliased modes being listed twice e.g.
```
Group CEA has 25 modes:
	 mode 3: 720x480 @ 60Hz 16:9, clock:27MHz progressive
	 mode 4: 1280x720 @ 60Hz 16:9, clock:74MHz progressive
	 mode 5: 1920x540 @ 60Hz 16:9, clock:74MHz interlaced
	 mode 16: 1920x1080 @ 60Hz 16:9, clock:148MHz progressive
	 mode 18: 720x576 @ 50Hz 16:9, clock:27MHz progressive
	 mode 19: 1280x720 @ 50Hz 16:9, clock:74MHz progressive
	 mode 31: 1920x1080 @ 50Hz 16:9, clock:148MHz progressive
	 mode 32: 1920x1080 @ 24Hz 16:9, clock:74MHz progressive
	 mode 33: 1920x1080 @ 25Hz 16:9, clock:74MHz progressive
	 mode 34: 1920x1080 @ 30Hz 16:9, clock:74MHz progressive
	 mode 40: 1920x540 @ 50Hz 16:9, clock:148MHz interlaced
	 mode 93: 3840x2160 @ 24Hz 16:9, clock:297MHz progressive
	 mode 94: 3840x2160 @ 25Hz 16:9, clock:297MHz progressive
	 mode 95: 3840x2160 @ 30Hz 16:9, clock:297MHz progressive
	 mode 96: 3840x2160 @ 50Hz 16:9, clock:594MHz progressive 
	 mode 96: 3840x2160 @ 50Hz 16:9, clock:594MHz progressive  <<<
	 mode 97: 3840x2160 @ 60Hz 16:9, clock:594MHz progressive
	 mode 97: 3840x2160 @ 60Hz 16:9, clock:594MHz progressive  <<<
	 mode 98: 4096x2160 @ 24Hz 256:135, clock:297MHz progressive
	 mode 99: 4096x2160 @ 25Hz 256:135, clock:297MHz progressive
	 mode 100: 4096x2160 @ 30Hz 256:135, clock:297MHz progressive
	 mode 101: 4096x2160 @ 50Hz 256:135, clock:594MHz progressive
	 mode 101: 4096x2160 @ 50Hz 256:135, clock:594MHz progressive  <<<
	 mode 102: 4096x2160 @ 60Hz 256:135, clock:594MHz progressive
	 mode 102: 4096x2160 @ 60Hz 256:135, clock:594MHz progressive  <<<
```
Unclear if the original `tvservice` would have done that, or if it would have culled them.  If that's the normal behavior I could cull them at the receiving end (the addon) instead.

I've tested the CEA modes on 3.14.  Going to move to 4.9 now for the DMT modes.

**Comment by hissingshark** [comment]
I'll merge it into the `dev` branch now so I can commit my changes to it.

**Comment by zjoasan** [comment]
Strange, but I think there are TV/monitors that support just one of the two DMT 47 for example, the lower horizontal resolution. If we don't detect that we can't use DMT 47 on those monitors, we could do a IF both are support just report the one with larger resolution. Not that I believe people will run high resolutions in their emulators.

I'm planning on using tv-service_shim for my Desktop addon too

**Pull request merged**
